[storage]
  [storage.redis]
    url=""

  [storage.mysql]
    #{username}:{password}@tcp({host}:{port})/{Dbname}?charset=utf8&parseTime=True&loc=Local
    dsn="root:root@tcp(192.168.90.35:3306)/nnr_device?charset=utf8"

[network_server]

[network_server.api]
  bing="0.0.0.0:8000"